### ISSUE TITLE
Food - "Reset to defaults" reveals unrelated dietary options

### ISSUE THREAD

**Issue by spaasis** [sykefi/climatediet#11]
1. Go to Food and choose a Vegetarian diet
2. Slide some food items
3. Press "Reset to defaults"
4. Behind the scenes the button changes the diet to Omnivore, so all the food item options are shown

**Comment by SaraKoskelainen** [comment]
Hmm, I had made it working correctly previously so that "Reset to defaults" set values to default values of the selected diet, so I must have broke something afterwards, I'll have look.

**Comment by SaraKoskelainen** [comment]
Ah, this is an old issue. This is fixed in the food section update. I close this issue now.
